apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-resource
  namespace: common
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - http: 
      paths:
      - path: /
        backend:
          serviceName: entrypt
          servicePort: 81
      - path: /namespaces
        backend:  
          serviceName: entrypt
          servicePort: 8000 
