apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ingress-resource
  namespace: common
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - http: 
      paths:
      - path: /api
        backend:
          serviceName: backend
          servicePort: 31064
      - path: /
        backend:
          serviceName: frontend
          servicePort: 31064

        