apiVersion: apps/v1
kind: Deployment
metadata:
  name: flaskapp
  namespace: common
  labels:
    app: flaskapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flaskapp
  template:
    metadata:
      labels:
        app: flaskapp
    spec:
      containers:
      - name: flaskapp
        image: "gcr.io/testing-project-272008/flaskapp:hood"
        ports:
        - containerPort: 5000