apiVersion: v1
kind: Service
metadata:
  name: entrypt
  namespace: common
spec:
  type: LoadBalancer
  ports:
  - name: backend
    port: 8080
    targetPort: 5000
  - name: frontend
    port: 81
    targetPort: 80
  selector:
    app: hoodapp