apiVersion: apps/v1
kind: Deployment
metadata:
  name: react
  namespace: common
  labels:
    app: react
spec:
  replicas: 1
  selector:
    matchLabels:
      app: react
  template:
    metadata:
      labels:
        app: react
    spec:
      containers:
      - name: react
        image: "gcr.io/testing-project-272008/react:nginx"
        ports:
        - containerPort: 80